zp = int(input('Введите заработанную плату в месяц: '))
ipoteka = int(input('Введите сколько процентов уходит на ипотеку: '))
life = int(input('Введите сколько процентов уходит на жизнь: '))
premia = int(input('Введите количество премий за год: '))
print('На ипотеку было потрачено:', int(12 * (zp * (ipoteka / 100))), 'рублей')
nakopleno = premia * zp / 2 + (100 - ipoteka - life) / 100 * (zp * 12)
print('Было накоплено:', int(nakopleno), 'рублей')
